name: "522"
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - altair=5.1
  - click=8.1
  - ipykernel=6.26
  - jupyter-book=0.15
  - jupyter_contrib_nbextensions=0.7.0
  - jupyterlab-git=0.41
  - jupyterlab=4.0
  - matplotlib=3.8
  - myst-nb
  - numpy=1.26
  - pandas=2.1
  - pickleshare=0.7
  - pip=21.3
  - python=3.11
  - scikit-learn=1.3
  - scipy=1.11
  # commenting below to prevent errors with docker build
  # docker automatically installs these packages when installing altair
  # - vl-convert-python=1.1
  # - vegafusion=1.4
  # - vegafusion-python-embed=1.4
  # - vegafusion-jupyter=1.4
  # - vega_datasets=0.9.0
  - pip:
      - dataframe-image==0.2.2
      - vl-convert-python==1.1 # need this for docker build
      - vegafusion==1.4.5
      - vegafusion-python-embed==1.4.5
